name: Codex Evolutionary Auto PR
on:
  workflow_dispatch:
  push:
    branches:
      - evo/*
permissions:
  contents: write
  pull-requests: write
env:
  GITHUB_TOKEN: ${{ secrets.CODEX_GH_TOKEN }}
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create PR
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          gh pr create \
            --title "Evo PR: $BRANCH" \
            --body "Automated evolutionary PR by Codex swarm" \
            --base main || true
  evaluate-and-merge:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - uses: actions/checkout@v4
      - name: Select best performing PR
        run: |
          echo "Evaluating Codex PR performance metrics..."
          gh pr list --state open --search "Evo PR" || true
          # Selection logic: merge only CI-passed, minimal diff PRs
          BEST=$(gh pr list --state open --json number,statusCheckRollup \
            --jq '.[] | select(.statusCheckRollup[]?.conclusion=="SUCCESS") | .number' | head -n 1)
          if [ -n "$BEST" ]; then
            gh pr merge $BEST --auto --squash --delete-branch
            echo "✅ Merged PR #$BEST"
          else
            echo "⚠️ No successful PR found, manual review needed."
          fi
