---
name: Cleanup Branches

"on":
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run weekly on Sundays at midnight UTC
    - cron: '0 0 * * 0'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete branches other than main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all remote branches..."

          # Get all remote branches except main using ls-remote
          branches=$(git ls-remote --heads origin | \
            awk '{print $2}' | \
            sed 's|refs/heads/||' | \
            grep -v '^main$' || true)

          if [ -z "$branches" ]; then
            echo "No branches to delete. Only main branch exists."
            exit 0
          fi

          echo "Branches to delete:"
          echo "$branches"

          # Delete each branch
          while IFS= read -r branch; do
            if [ -n "$branch" ]; then
              echo "Deleting branch: $branch"
              git push origin --delete "$branch" || \
                echo "Failed to delete $branch"
            fi
          done <<< "$branches"

          echo "Branch cleanup completed!"
